embedding_size: [64]
feat_embed_dim: 64

n_mm_layers: 1
num_layers: [2]
knn_k: [10]
mm_image_weight: 0.1
num_freq_bands: [3]
ib_direction: ['Pos']
ib_alpha: [1.0]
ib_mu: [1.0]
ib_phi_plus: [0.0]
aggr_mode: ['add']
learning_rate: [0.0001]
reg_weight: [0.00]
ib_weight: [0.01]
hyper_parameters: ["embedding_size","knn_k", "aggr_mode", "reg_weight", "learning_rate","ib_weight","num_layers","num_freq_bands","ib_direction", "ib_alpha", "ib_mu", "ib_phi_plus"]
